### ISSUE TITLE
STN calibration

### ISSUE THREAD

**Issue by KamalM8** [rohitrango/STNAdversarial#1]
Hi Rohit, 

Thanks for the great work. In your paper, you mentioned that the values of lambda are obtained via "coarse grid search". I am trying to replicate your results on Omniglot and miniImageNet. Can you share with me the final STN lambda parameters that you used for both experiments?

Best wishes
Kamal

**Comment by rohitrango** [comment]
Try lambda = 1,5,7,10 for a range of coarse values.
